# Generated by Django 4.1.5 on 2023-02-03 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_url_number_clicks_alter_url_original_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='short_url',
            new_name='hash',
        ),
    ]
